# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/payflow
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Server
server.port=8081